name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download JDK 17 distribution
        uses: actions/download-artifact@v2
        with:
          name: jdk-distribution
          path: jdk-distribution.zip

      - name: Extract JDK 17 distribution
        run: |
          unzip jdk-distribution.zip -d $HOME/jdk17
          echo "export JAVA_HOME=$HOME/jdk17" >> $GITHUB_ENV
          echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> $GITHUB_ENV

      - name: Set up JDK 17
        run: |
          source $GITHUB_ENV
          java -version

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
        env:
          USERNAME: ${{ env.MY_GITHUB_USERNAME }}
          TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
