name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Set up Java JDK
      uses: actions/setup-java@v1.4.4
      with:
        distribution: corretto
        java-version: '17'
        java-package: 'jdk'
        server-id: 'github'
        settings-path: ${{ github.workspace }}

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
