name: Java CI with Gradle

on:
  release:
    types: [created]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Print workspace contents
        run: ls -R
        
      - name: Commit build artifacts
        env:
            GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git config user.name "Arktikus"
          git config user.email "ArktikusArkan@gmail.com"
          git add build
          git commit -m "Add build artifacts"
          git remote set-url origin https://${GH_TOKEN}@github.com/Arktikus/frostbite.git
          git push origin HEAD:main

      - name: Determine JAR file name
        id: jar-file
        run: |
          tag=$(git describe --abbrev=0 --tags)
          echo "::set-output name=jar-file::$(find ./build/libs/ -name "frostbite-${tag}.jar" -print -quit)"

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/libs/frostbite-${{ steps.jar-file.outputs.jar-file }}
          asset_name: frostbite-${{ steps.jar-file.outputs.jar-file }}
          asset_content_type: application/java-archive
