name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java JDK
      run: |
        curl -sL https://github.com/actions/setup-java/releases/latest/download/install-jdk.sh -o install-jdk.sh
        chmod +x install-jdk.sh
        ./install-jdk.sh --url "https://github.com/AdoptOpenJDK/openjdk17-binaries/releases/download/jdk-17%2B35/OpenJDK17-jdk_x64_linux_hotspot_17_35.tar.gz" --dir /opt/hostedtoolcache/Java
        export JAVA_HOME="/opt/hostedtoolcache/Java/jdk-17+35"
        export PATH="$JAVA_HOME/bin:$PATH"

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to GitHub Packages
      run: |
        echo "MY_GITHUB_USERNAME=${{ secrets.MY_GITHUB_USERNAME }}" >> $GITHUB_ENV
        echo "MY_GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}" >> $GITHUB_ENV
        ./gradlew publish
      env:
        MY_GITHUB_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
